export const MODAL_PDF = 'MODAL_PDF'
export const MODAL_ENTIDAD = 'MODAL_ENTIDAD'
export const URL_PDF = 'URL_PDF'
export const ENTIDAD_SELECTED = 'ENTIDAD_SELECTED'
export const ENTIDADES = 'ENTIDADES'
export const RESOLUCIONES = 'RESOLUCIONES'
export const YEARS = 'YEARS'
